#%RAML 0.8

title: DevOps Portal API
version: v1
mediaType: application/json

/api/:
  get:
    description: "List of available API versions"
    responses:
      200:
        body:
          schema: !include schemas/200.json
          example: !include response_examples/200/versions.json

/api/{version}:
  uriParameters:
    version:
      description: "API version"
      type: string

  /regions:
    get:
      description: "List of regions"
      responses:
        200:
          body:
            schema: !include schemas/200.json
            example: !include response_examples/200/regions.json

  /regions/detailed:
    get:
      description: "Detailed information about regions."
      responses:
        200:
          body:
            schema: !include schemas/200.json
            example: !include response_examples/200/regions_detailed.json

  /infra:
    get:
      description: "Information about infrastructure services for all regions"
      responses:
        200:
          body:
            schema: !include schemas/200.json
            example: !include response_examples/200/infra.json
        404:
          body:
            schema: !include schemas/404.json
            example: !include response_examples/404/region.json

  /security/issues/{period}:
    uriParameters:
      period:
        description: "Return issues discovered at specific period"
        enum: ["day", "week", "month"]
    get:
      description: "Return list of Issue objects"
      responses:
        200:
          body:
            schema: !include schemas/200.json
            example: !include response_examples/200/security_issues.json

  /region/{region}:
    uriParameters:
      region:
        description: "Region name which is region identifier"
        type: string

    /status/{period}:
      uriParameters:
        period:
          description: "Return data for specific period: day, week, month"
          type: string
      get:
        description: "Overview of region's services status"
        responses:
          200:
            body:
              schema: !include schemas/200.json
              example: !include response_examples/200/status.json
          404:
            body:
              schema: !include schemas/404.json
              example: !include response_examples/404/region.json

    /security/issues/{period}:
      uriParameters:
        period:
          description: "Return issues discovered at specific period"
          enum: ["day", "week", "month"]
      get:
        description: "Return list of Issue objects"
        responses:
          200:
            body:
              schema: !include schemas/200.json
              example: !include response_examples/200/security_issues.json

    /status/health/{period}:
      uriParameters:
        period:
          description: "Return data for specific period: day, week, month"
          type: string
      get:
        description: "Region health data aggregated per service"
        responses:
          200:
            body:
              schema: !include schemas/200.json
              example: !include response_examples/200/status_region_health.json
          404:
            body:
              schema: !include schemas/404.json
              example: !include response_examples/404/region.json

    /status/availability/{period}:
      uriParameters:
        period:
          description: "Return data for specific period: day, week, month"
          type: string
      get:
        description: "Region availability data aggregated per service"
        responses:
          200:
            body:
              schema: !include schemas/200.json
              example: !include response_examples/200/status_region_availability.json
          404:
            body:
              schema: !include schemas/404.json
              example: !include response_examples/404/region.json

    /status/performance/{period}:
      uriParameters:
        period:
          description: "Return data for specific period: day, week, month"
          type: string
      get:
        description: "Region performance data aggregated per service"
        responses:
          200:
            body:
              schema: !include schemas/200.json
              example: !include response_examples/200/status_region_performance.json
          404:
            body:
              schema: !include schemas/404.json
              example: !include response_examples/404/region.json

    /runbooks:
      get:
        description: List all runbooks for current region
        responses:
          200:
            body:
              schema: !include schemas/200.json
              example: !include response_examples/200/runbooks.json
          404:
            body:
              schema: !include schemas/404.json
      post:
        description: Create a new runbook
        body:
          application/json:
            formParameters: !include forms/runbook.yaml
        responses:
          201:
            body:
              schema: !include schemas/200.json
              example: !include response_examples/200/single_runbook.json
          400:
            body:
              schema: !include schemas/404.json

      /{runbook_id}:
        uriParameters:
          runbook_id:
            description: Id of a particular runbook
            type: string
        get:
          description: Get a particular runbook
          responses:
            200:
              body:
                schema: !include schemas/200.json
                example: !include response_examples/200/single_runbook.json
            404:
              body:
                schema: !include schemas/404.json
        put:
          body:
            application/json:
              formParameters: !include forms/runbook.yaml
          description: Update contents of a runbook
          responses:
            200:
              body:
                schema: !include schemas/200.json
                example: !include response_examples/200/single_runbook.json
            400:
              body:
                schema: !include schemas/404.json
            404:
              body:
                schema: !include schemas/404.json
        delete:
          description: Delete a runbook
          responses:
            204:
            404:
              body:
                schema: !include schemas/404.json
        /run:
          post:
            description: Schedule a run of the runbook
            responses:
              202:
                body:
                  schema: !include schemas/200.json
              404:
                body:
                  schema: !include schemas/404.json
        /runs:
          get:
            description: Get list of all runs of a runbook
            responses:
              200:
                body:
                  schema: !include schemas/200.json
                  example: !include response_examples/200/runbook_runs.json
              404:
                body:
                  schema: !include schemas/404.json
          /{run_id}:
            uriParameters:
              run_id:
                description: id of a runbook run
                type: string
            get:
              description: Get information and description of a run of the runbook
              responses:
                200:
                  body:
                    schema: !include schemas/200.json
                    example: !include response_examples/200/single_runbook_run.json
                404:
                  body:
                    schema: !include schemas/404.json

    /infra:
      get:
        description: "Information about region's infrastructure services"
        responses:
          200:
            body:
              schema: !include schemas/200.json
              example: !include response_examples/200/infra_region.json
          404:
            body:
              schema: !include schemas/404.json
              example: !include response_examples/404/region.json

  /status/{period}:
    uriParameters:
      period:
        description: "Return data for specific period: day, week, month"
        type: string
    get:
      description: "Overview data aggregated per region"
      responses:
        200:
          body:
            schema: !include schemas/200.json
            example: !include response_examples/200/status.json

  /status/health/{period}:
    uriParameters:
      period:
        description: "Return data for specific period: day, week, month"
        type: string
    get:
      description: "Health data aggregated per region"
      responses:
        200:
          body:
            schema: !include schemas/200.json
            example: !include response_examples/200/status_health.json

  /status/availability/{period}:
    uriParameters:
      period:
        description: "Return data for specific period: day, week, month"
        type: string
    get:
      description: "Availability data aggregated per region"
      responses:
        200:
          body:
            schema: !include schemas/200.json
            example: !include response_examples/200/status_availability.json

  /status/performance/{period}:
    uriParameters:
      period:
        description: "Return data for specific period: day, week, month"
        type: string
    get:
      description: "Performance data aggregated per region"
      responses:
        200:
          body:
            schema: !include schemas/200.json
            example: !include response_examples/200/status_performance.json
